system_message_file: templates/simplified_system_message.txt

prompt_template_dir: templates/
prompts:
    - simplified_prompt.txt:
        num_completions: 5

nudge_prompts: "nudges.txt"

llm_input_file_path: "oneloop_onemethod_2.txt"
