system_message_file: templates/simplified_system_message.txt

prompt_template_dir: templates/
prompts:
    - simplified_prompt.txt:
        num_completions: 5
        
nudge_prompts: "templates/nudges.txt"

llm_input_file_path: "experiments/missing_files.txt"
