checker: frama-c
model: gpt-4
model_host: azure-openai
benchmarks: experiments/array_files.txt
benchmark_features: arrays_pointers_multiple_loops
use_json_output: True
analysis: 
- loop_invariants
debug: True
