system_message_file: ../templates/classification_system_message.txt

prompt_template_dir: ../templates/
prompts:
    - classification_prompt.txt:
        num_completions: 5

llm_input_file_path: "../experiments/classification.txt"
