checker: frama-c

provider: local

benchmarks: experiments/diff_files.txt

benchmark_features: "one_loop_one_method"

analysis:
    - loop_invariants

loopy_sequence:
    - prompt_llm:
        system_text: templates/simplified_system_message.txt
        prompt_text: templates/simplified_prompt.txt
        num_completions: 15
        extract_annotation: loop_invariants
    - check_individual_completion
    - houdini_for_individual_completion
    - houdini_for_combined_completion