system_message_file: ../templates/simplified_system_message.txt

prompt_template_dir: ../templates/
prompts:
    - example_2.txt:
        set_output: "example_2_ans.txt"
    - simplified_prompt_with_nudges.txt:
        num_completions: 10
        
healing_template_dir: ../templates/
healing_prompts:
    - simplified_healing_prompt.txt:
        num_completions: 1

nudge_prompts: "../templates/nudges.txt"

llm_input_file_path: "../experiments/failed_benchmarks_1.txt"
