system_message_file: ../templates/system_message_non_termination.txt

prompt_template_dir: ../templates/
prompts:
    - simplified_prompt_non_termination.txt:
        num_completions: 1

llm_input_file_path: "../experiments/non_termination_benchmarks.txt"
