checker: frama-c # only frama-c is supported for now, there is a boogie PoC
checker_timeout: 3 # in seconds
model: gpt-4-32k # gpt-4, gpt-3.5-turbo, codellama-34b-python
benchmarks: experiments/loop_invariants.txt # list of benchmark files
benchmark_features: one_loop_one_method # features of the benchmark. Possible values: {one_loop_one_method, multiple_methods_no_loops, arrays_pointers_multiple_loops, termination_one_loop_one_method}
debug: True # if True, prints debug information
