checker: frama-c
model: gpt-4
model_host: azure-openai
benchmarks: experiments/svcomp_true_ultimate_false_with_filters_for_definition.txt
benchmark_features: multiple_loops_multiple_methods
use_json_output: True
debug: True
