checker: frama-c

benchmarks: experiments/svcomp_reachsafety_filtered.txt

benchmark_features: "multiple_loops_multiple_methods"

analysis:
    - loop_invariants
    - pre_post_conditions

loopy_sequence:
    - prompt_llm:
        system_text: templates/abc.txt
        prompt_text: templates/abc.txt
        num_completions: 5
        extract_annotation: loop_variants
    - check:
        loop_invariants
    - houdini_individual_completion:
        loop_invariants
    - houdini_for_combined_completion:
        loop_invariants
