checker: frama-c
model: gpt-4
model_host: azure-openai
benchmarks: experiments/svcomp_positive_set_without_nla.txt
benchmark_features: multiple_loops_multiple_methods
use_json_output: True
debug: True
