checker: frama-c

analysis: termination_one_loop_one_method

system_message_file: ../templates/system_message_non_termination.txt

prompt_template_dir: ../templates/
prompts:
    - simplified_prompt_non_termination.txt:
        num_completions: 5

llm_input_file_path: "../experiments/termination.txt"
