checker: frama-c

benchmarks: experiments/filtered_termination_positive.txt

benchmark_features: "one_loop_one_method"

analysis:
    - loop_invariants
    - loop_variants

loopy_sequence:
    - prompt_llm:
        system_text: templates/termination_variants_system.txt
        prompt_text: templates/termination_variants_prompt.txt
        num_completions: 5
        extract_annotation: loop_variants
    - prompt_llm_for_each_existing_annotation:
        system_text: templates/termination_invariants_system.txt
        prompt_text: templates/termination_invariants_prompt.txt
        num_completions: 5
        extract_annotation: loop_invariants
    - check:
        loop_invariants
    - houdini_individual_completion:
        loop_invariants
    - houdini_for_combined_completion:
        loop_invariants
    - check:
        loop_invariants
        loop_variants