checker: frama-c

benchmarks: experiments/termination_one_loop_one_method.txt

benchmark_features: "one_loop_one_method"

analysis:
    - loop_invariants
    - loop_variants

loopy_sequence:
    - prompt_llm:
        system_text: templates/simplified_system_message.txt
        prompt_text: templates/simplified_prompt_with_nudges.txt
        num_completions: 3
        extract_annotation: loop_invariants
    - check_individual_completion
    - houdini_for_individual_completion
    - houdini_for_combined_completion
    - prompt_llm:
        system_text: templates/termination_system_v1.txt
        prompt_text: templates/termination_prompt_v1.txt
        num_completions: 2
        extract_annotation: loop_variants
    - check_individual_completion
