prompts:
    - CoT1.txt
    - CoT2.txt:
        set_output: CoT2_answer.txt
    - CoT3.txt: 
        num_completions: 3
    - CoT4.txt:
        temperature: 0.1

healing_prompts:
    - repair1.txt
    - repair2.txt
    - repair3.txt:
        temperature: 0.1

num_retries: 5

checker_cmd:
    boogie /timeout:10 {input_file}

benchmark:
    file1

checker_msg:
    \"1 verified\" in message

raw_input_to_checker_input:
    boogie_translator

checker_input_with_llm_output:
    llm_parser_with_boogie

