prompt_template_dir: ../pipeline/templates/
prompts:
    - CoT1.txt
    - CoT2.txt:
        set_output: CoT2_answer.txt
    - CoT3.txt: 
        num_completions: 3
    - CoT4.txt:
        temperature: 0.1

healing_template_dir: ../healing/templates/
healing_prompts:
    - repair1.txt
    - repair2.txt
    - repair3.txt:
        temperature: 0.1

healing_retries: 5

llm_input_dir: ../pipeline/c_benchmarks/code2inv

checker_input_dir: ../pipeline/trusted_boogie_code/code2inv
