system_message_file: ../pipeline/templates/simplified_system_message.txt

prompt_template_dir: ../pipeline/templates/
prompts:
    - simplified_prompt.txt:
        num_completions: 5

nudge_prompts: "nudges.txt"

llm_input_file_path: "single_loop_benchmarks_2.txt"
