system_message_file: ../pipeline/templates/simplified_system_message.txt

prompt_template_dir: ../pipeline/templates/
prompts:
    - simplified_prompt.txt:
        num_completions: 2



llm_input_dir: ../pipeline/c_benchmarks/code2inv
